### ISSUE TITLE
Umbrella issue for graphql-loadtest-electron@1.0.0

### ISSUE THREAD

**Issue by marhaupe** [marhaupe/graphql-loadtest#13]
- [ ]  Add documentation / tooltips to the settings page
- [ ]  Improve error handling
- [ ] Persistence
- [ ] Fix the bug where typing the last character of an url won't clear the error message eventhough the url now is valid
- [ ] Fix UI stuff. Maybe graphiql@1.0.0 will make some things easier. Consider waiting for this release
- [ ] Add option to stop a loadtest
- [ ] Find a better solution for the result streaming between renderer and main process. Research if service-workers can help here
- [ ] Improve READMEs
